import { Recipe } from "./types";

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    title: "Rainbow Veggie Wraps",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 92,
    ingredients: ["Tortillas", "Hummus", "Carrots", "Cucumber", "Bell peppers", "Cheese"],
    steps: ["Spread hummus on tortilla", "Layer sliced veggies", "Add cheese", "Roll tightly and slice"],
    tags: ["Quick", "No-Cook", "Veggie"],
    emoji: "🌯",
    cuisine: "Mediterranean",
    nutrition: { calories: 220, protein: 8, carbs: 28, fat: 9, fiber: 4 },
  },
  {
    id: "2",
    title: "Mini Pizza Faces",
    cookTime: "20 min",
    difficulty: "Easy",
    servings: 6,
    kidApproval: 98,
    ingredients: ["English muffins", "Pizza sauce", "Mozzarella", "Olives", "Cherry tomatoes", "Peppers"],
    steps: ["Preheat oven to 375°F", "Spread sauce on muffin halves", "Add cheese and toppings as faces", "Bake 10-12 minutes"],
    tags: ["Fun", "Kid-Favorite", "Interactive"],
    emoji: "🍕",
    cuisine: "Italian",
    nutrition: { calories: 280, protein: 12, carbs: 30, fat: 12, fiber: 2 },
  },
  {
    id: "3",
    title: "Banana Oat Pancakes",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 95,
    ingredients: ["Bananas", "Oats", "Eggs", "Cinnamon", "Honey", "Blueberries"],
    steps: ["Blend banana, oats, eggs and cinnamon", "Pour small circles on pan", "Cook 2 min each side", "Top with berries"],
    tags: ["Breakfast", "Healthy", "No Sugar Added"],
    emoji: "🥞",
    cuisine: "American",
    nutrition: { calories: 195, protein: 7, carbs: 32, fat: 5, fiber: 3 },
  },
  {
    id: "4",
    title: "Cheesy Broccoli Bites",
    cookTime: "25 min",
    difficulty: "Medium",
    servings: 12,
    kidApproval: 87,
    ingredients: ["Broccoli", "Cheddar cheese", "Breadcrumbs", "Eggs", "Garlic powder"],
    steps: ["Steam and chop broccoli", "Mix with cheese, breadcrumbs, egg", "Form into small balls", "Bake at 400°F for 15 min"],
    tags: ["Veggie Hidden", "Snack", "Freezer-Friendly"],
    emoji: "🥦",
    cuisine: "American",
    nutrition: { calories: 85, protein: 5, carbs: 8, fat: 4, fiber: 1 },
  },
  {
    id: "5",
    title: "Peanut Butter Noodles",
    cookTime: "12 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 90,
    ingredients: ["Spaghetti", "Peanut butter", "Soy sauce", "Honey", "Lime", "Carrots"],
    steps: ["Cook pasta al dente", "Whisk PB, soy, honey, lime", "Toss pasta with sauce", "Top with shredded carrots"],
    tags: ["Quick", "Protein-Rich", "One-Pot"],
    emoji: "🍝",
    cuisine: "Thai",
    nutrition: { calories: 340, protein: 14, carbs: 42, fat: 13, fiber: 3 },
  },
  {
    id: "6",
    title: "Berry Smoothie Bowl",
    cookTime: "5 min",
    difficulty: "Easy",
    servings: 2,
    kidApproval: 94,
    ingredients: ["Mixed berries", "Banana", "Yogurt", "Granola", "Chia seeds", "Honey"],
    steps: ["Blend berries, banana, yogurt until thick", "Pour into bowls", "Top with granola and chia", "Drizzle honey"],
    tags: ["Breakfast", "No-Cook", "Healthy"],
    emoji: "🫐",
    cuisine: "American",
    nutrition: { calories: 250, protein: 8, carbs: 45, fat: 5, fiber: 6 },
  },
  {
    id: "7",
    title: "Chicken Quesadillas",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 96,
    ingredients: ["Tortillas", "Shredded chicken", "Cheddar cheese", "Bell peppers", "Sour cream", "Salsa"],
    steps: ["Layer cheese and chicken on tortilla", "Add diced peppers", "Fold and cook on pan 3 min each side", "Slice into wedges"],
    tags: ["Quick", "Kid-Favorite", "Protein-Rich"],
    emoji: "🫔",
    cuisine: "Mexican",
    nutrition: { calories: 320, protein: 22, carbs: 28, fat: 14, fiber: 2 },
  },
  {
    id: "8",
    title: "Veggie Fried Rice",
    cookTime: "20 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 88,
    ingredients: ["Cooked rice", "Eggs", "Frozen peas & carrots", "Soy sauce", "Sesame oil", "Green onions"],
    steps: ["Scramble eggs in hot pan", "Add veggies and rice", "Season with soy sauce and sesame oil", "Toss and serve"],
    tags: ["One-Pot", "Veggie", "Leftover-Friendly"],
    emoji: "🍚",
    cuisine: "Chinese",
    nutrition: { calories: 260, protein: 9, carbs: 38, fat: 8, fiber: 3 },
  },
  {
    id: "9",
    title: "Fish Stick Tacos",
    cookTime: "18 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 85,
    ingredients: ["Fish sticks", "Small tortillas", "Shredded cabbage", "Lime", "Greek yogurt", "Avocado"],
    steps: ["Bake fish sticks per package directions", "Warm tortillas", "Top with cabbage, avocado, yogurt drizzle", "Squeeze lime on top"],
    tags: ["Fun", "Omega-3", "Interactive"],
    emoji: "🌮",
    cuisine: "Mexican",
    nutrition: { calories: 275, protein: 15, carbs: 30, fat: 11, fiber: 4 },
  },
  {
    id: "10",
    title: "Mac & Cheese Cups",
    cookTime: "25 min",
    difficulty: "Easy",
    servings: 12,
    kidApproval: 97,
    ingredients: ["Elbow macaroni", "Cheddar cheese", "Milk", "Butter", "Breadcrumbs", "Parmesan"],
    steps: ["Cook macaroni al dente", "Mix with cheese sauce", "Spoon into muffin tin", "Top with breadcrumbs and bake 12 min"],
    tags: ["Kid-Favorite", "Freezer-Friendly", "Fun"],
    emoji: "🧀",
    cuisine: "American",
    nutrition: { calories: 180, protein: 8, carbs: 22, fat: 7, fiber: 1 },
  },
  {
    id: "11",
    title: "Teriyaki Chicken Skewers",
    cookTime: "20 min",
    difficulty: "Medium",
    servings: 4,
    kidApproval: 91,
    ingredients: ["Chicken breast", "Teriyaki sauce", "Pineapple chunks", "Bell peppers", "Rice", "Sesame seeds"],
    steps: ["Cut chicken into cubes", "Thread onto skewers with pineapple and peppers", "Brush with teriyaki", "Grill or bake 12 min, serve over rice"],
    tags: ["Interactive", "Protein-Rich", "Sweet"],
    emoji: "🍢",
    cuisine: "Japanese",
    nutrition: { calories: 310, protein: 26, carbs: 35, fat: 6, fiber: 2 },
  },
  {
    id: "12",
    title: "Hidden Veggie Pasta Sauce",
    cookTime: "25 min",
    difficulty: "Easy",
    servings: 6,
    kidApproval: 93,
    ingredients: ["Pasta", "Tomato sauce", "Zucchini", "Carrots", "Spinach", "Parmesan"],
    steps: ["Blend zucchini, carrots, spinach into tomato sauce", "Simmer 10 min", "Cook pasta", "Toss and top with parmesan"],
    tags: ["Veggie Hidden", "Batch-Cook", "Classic"],
    emoji: "🍝",
    cuisine: "Italian",
    nutrition: { calories: 285, protein: 11, carbs: 42, fat: 8, fiber: 5 },
  },
  {
    id: "13",
    title: "Mini Meatball Soup",
    cookTime: "25 min",
    difficulty: "Medium",
    servings: 6,
    kidApproval: 89,
    ingredients: ["Ground turkey", "Chicken broth", "Small pasta", "Carrots", "Spinach", "Parmesan"],
    steps: ["Roll tiny meatballs from seasoned turkey", "Simmer in broth with carrots and pasta", "Add spinach last minute", "Serve with parmesan"],
    tags: ["Warm", "Protein-Rich", "Comforting"],
    emoji: "🍲",
    cuisine: "Italian",
    nutrition: { calories: 230, protein: 18, carbs: 22, fat: 7, fiber: 3 },
  },
  {
    id: "14",
    title: "Butter Chicken Mild",
    cookTime: "30 min",
    difficulty: "Medium",
    servings: 4,
    kidApproval: 86,
    ingredients: ["Chicken thighs", "Tomato puree", "Cream", "Butter", "Garam masala", "Rice"],
    steps: ["Cook chicken in butter", "Add tomato puree and mild spices", "Stir in cream and simmer 15 min", "Serve over rice"],
    tags: ["Mild", "Creamy", "Protein-Rich"],
    emoji: "🍛",
    cuisine: "Indian",
    nutrition: { calories: 350, protein: 24, carbs: 30, fat: 15, fiber: 2 },
  },
  {
    id: "15",
    title: "Fruit & Yogurt Parfait",
    cookTime: "5 min",
    difficulty: "Easy",
    servings: 2,
    kidApproval: 96,
    ingredients: ["Greek yogurt", "Granola", "Strawberries", "Blueberries", "Honey", "Chia seeds"],
    steps: ["Layer yogurt in glass", "Add granola and berries", "Repeat layers", "Drizzle honey and chia on top"],
    tags: ["Breakfast", "No-Cook", "Healthy"],
    emoji: "🍓",
    cuisine: "American",
    nutrition: { calories: 210, protein: 12, carbs: 32, fat: 5, fiber: 4 },
  },
  {
    id: "16",
    title: "Sweet Potato Fries & Dip",
    cookTime: "28 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 92,
    ingredients: ["Sweet potatoes", "Olive oil", "Paprika", "Garlic powder", "Greek yogurt", "Ketchup"],
    steps: ["Cut sweet potatoes into fries", "Toss with oil and spices", "Bake at 425°F for 22 min", "Serve with yogurt dip"],
    tags: ["Snack", "Healthy", "Veggie"],
    emoji: "🍠",
    cuisine: "American",
    nutrition: { calories: 185, protein: 4, carbs: 32, fat: 5, fiber: 5 },
  },
];

export const commonAllergies = [
  "Dairy", "Eggs", "Peanuts", "Tree Nuts", "Wheat/Gluten", "Soy", "Fish", "Shellfish",
];

export const commonDislikes = [
  "Spicy food", "Mushrooms", "Onions", "Tomatoes", "Broccoli", "Fish", "Beans", "Spinach",
];

export const commonFavorites = [
  "Pasta", "Pizza", "Chicken nuggets", "Mac & cheese", "Rice", "Fruits", "Pancakes", "Sandwiches",
];

export const cuisineOptions = [
  "Italian", "Mexican", "Indian", "Chinese", "Japanese", "Mediterranean", "American", "Thai",
];
