import { Recipe } from "./types";

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    title: "Rainbow Veggie Wraps",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 92,
    ingredients: ["Tortillas", "Hummus", "Carrots", "Cucumber", "Bell peppers", "Cheese"],
    steps: ["Spread hummus on tortilla", "Layer sliced veggies", "Add cheese", "Roll tightly and slice"],
    tags: ["Quick", "No-Cook", "Veggie"],
    icon: "salad",
    cuisine: "Mediterranean",
    nutrition: { calories: 220, protein: 8, carbs: 28, fat: 9, fiber: 4 },
  },
  {
    id: "2",
    title: "Mini Pizza Faces",
    cookTime: "20 min",
    difficulty: "Easy",
    servings: 6,
    kidApproval: 98,
    ingredients: ["English muffins", "Pizza sauce", "Mozzarella", "Olives", "Cherry tomatoes", "Peppers"],
    steps: ["Preheat oven to 375°F", "Spread sauce on muffin halves", "Add cheese and toppings as faces", "Bake 10-12 minutes"],
    tags: ["Fun", "Kid-Favorite", "Interactive"],
    icon: "pizza",
    cuisine: "Italian",
    nutrition: { calories: 280, protein: 12, carbs: 30, fat: 12, fiber: 2 },
  },
  {
    id: "3",
    title: "Banana Oat Pancakes",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 95,
    ingredients: ["Bananas", "Oats", "Eggs", "Cinnamon", "Blueberries", "Maple syrup"],
    steps: ["Blend banana, oats, eggs and cinnamon", "Pour small circles on pan", "Cook 2 min each side", "Top with berries"],
    tags: ["Breakfast", "Healthy", "No Sugar Added"],
    icon: "cake",
    cuisine: "American",
    nutrition: { calories: 195, protein: 7, carbs: 32, fat: 5, fiber: 3 },
  },
  {
    id: "4",
    title: "Spanakopita Bites",
    cookTime: "25 min",
    difficulty: "Easy",
    servings: 12,
    kidApproval: 86,
    ingredients: ["Spinach", "Feta cheese", "Phyllo dough", "Olive oil", "Dill", "Egg"],
    steps: ["Sauté spinach and mix with feta", "Cut phyllo into squares", "Fill and fold into triangles", "Bake at 375°F for 15 min"],
    tags: ["Veggie", "Snack", "Crispy"],
    icon: "leafy",
    cuisine: "Mediterranean",
    nutrition: { calories: 95, protein: 5, carbs: 10, fat: 5, fiber: 1 },
  },
  {
    id: "5",
    title: "Peanut Butter Noodles",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 90,
    ingredients: ["Spaghetti", "Peanut butter", "Soy sauce", "Honey", "Lime", "Carrots"],
    steps: ["Cook pasta al dente", "Whisk PB, soy, honey, lime", "Toss pasta with sauce", "Top with shredded carrots"],
    tags: ["Quick", "Protein-Rich", "One-Pot"],
    icon: "wheat",
    cuisine: "Thai",
    nutrition: { calories: 340, protein: 14, carbs: 42, fat: 13, fiber: 3 },
  },
  {
    id: "6",
    title: "Fattoush Salad",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 78,
    ingredients: ["Pita bread", "Cucumber", "Tomatoes", "Radishes", "Sumac", "Lemon dressing"],
    steps: ["Toast and break pita into chips", "Chop vegetables", "Toss with lemon dressing", "Sprinkle sumac on top"],
    tags: ["Quick", "Fresh", "Crunchy"],
    icon: "salad",
    cuisine: "Mediterranean",
    nutrition: { calories: 180, protein: 5, carbs: 26, fat: 7, fiber: 4 },
  },
  {
    id: "7",
    title: "Chicken Quesadillas",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 96,
    ingredients: ["Tortillas", "Cooked chicken", "Cheddar", "Bell peppers", "Sour cream", "Salsa"],
    steps: ["Layer cheese and chicken on tortilla", "Add diced peppers", "Fold and cook on pan 3 min each side", "Slice into wedges"],
    tags: ["Quick", "Kid-Favorite", "Protein-Rich"],
    icon: "drumstick",
    cuisine: "Mexican",
    nutrition: { calories: 320, protein: 22, carbs: 28, fat: 14, fiber: 2 },
  },
  {
    id: "8",
    title: "Veggie Fried Rice",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 89,
    ingredients: ["Cooked rice", "Eggs", "Peas", "Carrots", "Soy sauce", "Sesame oil"],
    steps: ["Scramble eggs in hot pan", "Add veggies and rice", "Season with soy sauce and sesame oil", "Toss and serve"],
    tags: ["One-Pot", "Veggie", "Leftover-Friendly"],
    icon: "utensils-crossed",
    cuisine: "Chinese",
    nutrition: { calories: 260, protein: 9, carbs: 38, fat: 8, fiber: 3 },
  },
  {
    id: "9",
    title: "Fish Stick Tacos",
    cookTime: "18 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 91,
    ingredients: ["Fish sticks", "Corn tortillas", "Shredded cabbage", "Avocado", "Yogurt", "Lime"],
    steps: ["Bake fish sticks per package directions", "Warm tortillas", "Top with cabbage, avocado, yogurt drizzle", "Squeeze lime on top"],
    tags: ["Fun", "Omega-3", "Interactive"],
    icon: "fish",
    cuisine: "Mexican",
    nutrition: { calories: 275, protein: 15, carbs: 30, fat: 11, fiber: 4 },
  },
  {
    id: "10",
    title: "Mac & Cheese Cups",
    cookTime: "25 min",
    difficulty: "Easy",
    servings: 12,
    kidApproval: 97,
    ingredients: ["Elbow macaroni", "Cheddar cheese", "Milk", "Butter", "Breadcrumbs", "Paprika"],
    steps: ["Cook macaroni al dente", "Mix with cheese sauce", "Spoon into muffin tin", "Top with breadcrumbs and bake 12 min"],
    tags: ["Kid-Favorite", "Freezer-Friendly", "Fun"],
    icon: "cookie",
    cuisine: "American",
    nutrition: { calories: 180, protein: 8, carbs: 22, fat: 7, fiber: 1 },
  },
  {
    id: "11",
    title: "Teriyaki Chicken Skewers",
    cookTime: "20 min",
    difficulty: "Medium",
    servings: 4,
    kidApproval: 93,
    ingredients: ["Chicken breast", "Pineapple", "Bell peppers", "Teriyaki sauce", "Rice", "Sesame seeds"],
    steps: ["Cut chicken into cubes", "Thread onto skewers with pineapple and peppers", "Brush with teriyaki", "Grill or bake 12 min, serve over rice"],
    tags: ["Interactive", "Protein-Rich", "Sweet"],
    icon: "beef",
    cuisine: "Japanese",
    nutrition: { calories: 310, protein: 26, carbs: 35, fat: 6, fiber: 2 },
  },
  {
    id: "12",
    title: "Hidden Veggie Pasta Sauce",
    cookTime: "20 min",
    difficulty: "Easy",
    servings: 6,
    kidApproval: 87,
    ingredients: ["Zucchini", "Carrots", "Spinach", "Tomato sauce", "Pasta", "Parmesan"],
    steps: ["Blend zucchini, carrots, spinach into tomato sauce", "Simmer 10 min", "Cook pasta", "Toss and top with parmesan"],
    tags: ["Veggie Hidden", "Batch-Cook", "Classic"],
    icon: "wheat",
    cuisine: "Italian",
    nutrition: { calories: 285, protein: 11, carbs: 42, fat: 8, fiber: 5 },
  },
  {
    id: "13",
    title: "Mini Meatball Soup",
    cookTime: "25 min",
    difficulty: "Medium",
    servings: 6,
    kidApproval: 91,
    ingredients: ["Ground turkey", "Tiny pasta", "Carrots", "Spinach", "Chicken broth", "Parmesan"],
    steps: ["Roll tiny meatballs from seasoned turkey", "Simmer in broth with carrots and pasta", "Add spinach last minute", "Serve with parmesan"],
    tags: ["Warm", "Protein-Rich", "Comforting"],
    icon: "soup",
    cuisine: "Italian",
    nutrition: { calories: 230, protein: 18, carbs: 22, fat: 7, fiber: 3 },
  },
  {
    id: "14",
    title: "Butter Chicken (Mild)",
    cookTime: "25 min",
    difficulty: "Medium",
    servings: 4,
    kidApproval: 89,
    ingredients: ["Chicken thighs", "Tomato puree", "Butter", "Cream", "Mild garam masala", "Rice"],
    steps: ["Cook chicken in butter", "Add tomato puree and mild spices", "Stir in cream and simmer 15 min", "Serve over rice"],
    tags: ["Mild", "Creamy", "Protein-Rich"],
    icon: "flame",
    cuisine: "Indian",
    nutrition: { calories: 350, protein: 24, carbs: 30, fat: 15, fiber: 2 },
  },
  {
    id: "15",
    title: "Fruit & Yogurt Parfait",
    cookTime: "5 min",
    difficulty: "Easy",
    servings: 2,
    kidApproval: 96,
    ingredients: ["Greek yogurt", "Granola", "Strawberries", "Blueberries", "Honey", "Chia seeds"],
    steps: ["Layer yogurt in glass", "Add granola and berries", "Repeat layers", "Drizzle honey and chia on top"],
    tags: ["Breakfast", "No-Cook", "Healthy"],
    icon: "cherry",
    cuisine: "American",
    nutrition: { calories: 210, protein: 12, carbs: 32, fat: 5, fiber: 4 },
  },
  {
    id: "16",
    title: "Sweet Potato Fries & Dip",
    cookTime: "28 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 92,
    ingredients: ["Sweet potatoes", "Olive oil", "Paprika", "Garlic powder", "Greek yogurt", "Ketchup"],
    steps: ["Cut sweet potatoes into fries", "Toss with oil and spices", "Bake at 425°F for 22 min", "Serve with yogurt dip"],
    tags: ["Snack", "Healthy", "Veggie"],
    icon: "carrot",
    cuisine: "American",
    nutrition: { calories: 185, protein: 4, carbs: 32, fat: 5, fiber: 5 },
  },
  {
    id: "17",
    title: "Veggie Pulao",
    cookTime: "25 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 90,
    ingredients: ["Basmati rice", "Mixed veggies", "Ghee", "Cumin seeds", "Bay leaf", "Green peas"],
    steps: ["Sauté cumin and bay leaf in ghee", "Add veggies and rice", "Add water and cook covered 15 min", "Fluff with fork and serve"],
    tags: ["One-Pot", "Veggie", "Mild"],
    icon: "utensils-crossed",
    cuisine: "Indian",
    nutrition: { calories: 270, protein: 6, carbs: 45, fat: 7, fiber: 3 },
  },
  {
    id: "18",
    title: "Mini Dosa with Chutney",
    cookTime: "20 min",
    difficulty: "Medium",
    servings: 6,
    kidApproval: 88,
    ingredients: ["Dosa batter", "Ghee", "Coconut chutney", "Potatoes", "Mustard seeds", "Curry leaves"],
    steps: ["Heat pan and spread batter thin", "Drizzle ghee, cook until crispy", "Fill with potato masala", "Serve with coconut chutney"],
    tags: ["Crispy", "South Indian", "Fun"],
    icon: "croissant",
    cuisine: "Indian",
    nutrition: { calories: 195, protein: 5, carbs: 30, fat: 6, fiber: 2 },
  },
  {
    id: "19",
    title: "Aloo Paratha",
    cookTime: "25 min",
    difficulty: "Medium",
    servings: 4,
    kidApproval: 94,
    ingredients: ["Whole wheat flour", "Potatoes", "Butter", "Cumin powder", "Coriander", "Yogurt"],
    steps: ["Make dough and potato filling", "Stuff dough balls with filling", "Roll out and cook on tawa with butter", "Serve with yogurt"],
    tags: ["North Indian", "Comforting", "Kid-Favorite"],
    icon: "croissant",
    cuisine: "Indian",
    nutrition: { calories: 240, protein: 6, carbs: 35, fat: 9, fiber: 3 },
  },
  {
    id: "20",
    title: "Paneer Tikka Bites",
    cookTime: "20 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 91,
    ingredients: ["Paneer", "Yogurt", "Turmeric", "Bell peppers", "Lemon", "Chaat masala"],
    steps: ["Cube paneer and marinate in spiced yogurt", "Thread onto skewers with peppers", "Grill or bake 12 min", "Squeeze lemon and sprinkle chaat masala"],
    tags: ["Protein-Rich", "Interactive", "Mild"],
    icon: "beef",
    cuisine: "Indian",
    nutrition: { calories: 220, protein: 14, carbs: 8, fat: 15, fiber: 1 },
  },
  {
    id: "21",
    title: "Dal Tadka",
    cookTime: "25 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 85,
    ingredients: ["Yellow lentils", "Tomatoes", "Garlic", "Cumin", "Ghee", "Rice"],
    steps: ["Boil lentils until soft", "Prepare tadka with ghee, garlic, cumin", "Pour over lentils with tomatoes", "Serve over steamed rice"],
    tags: ["Protein-Rich", "Comforting", "Mild"],
    icon: "soup",
    cuisine: "Indian",
    nutrition: { calories: 260, protein: 14, carbs: 38, fat: 6, fiber: 8 },
  },
  {
    id: "22",
    title: "Idli with Sambar",
    cookTime: "20 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 87,
    ingredients: ["Idli batter", "Mixed veggies", "Sambar powder", "Tamarind", "Mustard seeds", "Coconut chutney"],
    steps: ["Steam idli batter in moulds for 10 min", "Cook veggies in tamarind sambar", "Temper with mustard seeds", "Serve idlis with sambar and chutney"],
    tags: ["South Indian", "Healthy", "Steamed"],
    icon: "circle",
    cuisine: "Indian",
    nutrition: { calories: 180, protein: 7, carbs: 32, fat: 3, fiber: 4 },
  },
  {
    id: "23",
    title: "Chole Rice Bowl",
    cookTime: "25 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 86,
    ingredients: ["Chickpeas", "Onion", "Tomatoes", "Chole masala", "Rice", "Lemon"],
    steps: ["Sauté onions and tomatoes", "Add chickpeas and chole masala", "Simmer 15 min", "Serve over rice with lemon squeeze"],
    tags: ["Protein-Rich", "Mild", "One-Pot"],
    icon: "bean",
    cuisine: "Indian",
    nutrition: { calories: 290, protein: 12, carbs: 45, fat: 6, fiber: 9 },
  },
  {
    id: "24",
    title: "Khichdi",
    cookTime: "20 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 83,
    ingredients: ["Rice", "Moong dal", "Ghee", "Turmeric", "Cumin", "Mixed veggies"],
    steps: ["Wash rice and dal together", "Pressure cook with veggies, turmeric, water", "Temper with ghee and cumin", "Serve warm with a dollop of ghee"],
    tags: ["Comfort Food", "One-Pot", "Gentle"],
    icon: "flame",
    cuisine: "Indian",
    nutrition: { calories: 230, protein: 9, carbs: 38, fat: 5, fiber: 4 },
  },
  {
    id: "25",
    title: "Poha (Flattened Rice)",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 91,
    ingredients: ["Flattened rice", "Onion", "Green peas", "Peanuts", "Turmeric", "Lemon"],
    steps: ["Rinse and drain poha", "Sauté onion, peanuts, peas", "Add turmeric and poha, toss", "Squeeze lemon and serve"],
    tags: ["Quick", "Mild", "Breakfast"],
    icon: "utensils-crossed",
    cuisine: "Indian",
    nutrition: { calories: 200, protein: 5, carbs: 32, fat: 6, fiber: 2 },
  },
  {
    id: "26",
    title: "Bread Upma",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 3,
    kidApproval: 85,
    ingredients: ["Bread slices", "Onion", "Tomato", "Mustard seeds", "Curry leaves", "Green chili"],
    steps: ["Cube and lightly toast bread", "Temper mustard seeds and curry leaves", "Add onion, tomato, sauté", "Toss in bread cubes and serve"],
    tags: ["Quick", "Budget", "Breakfast"],
    icon: "sandwich",
    cuisine: "Indian",
    nutrition: { calories: 180, protein: 5, carbs: 28, fat: 5, fiber: 2 },
  },
  {
    id: "27",
    title: "Curd Rice",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 88,
    ingredients: ["Cooked rice", "Yogurt", "Mustard seeds", "Curry leaves", "Pomegranate seeds", "Salt"],
    steps: ["Mix cooled rice with yogurt", "Temper mustard seeds and curry leaves", "Pour over rice and mix", "Garnish with pomegranate"],
    tags: ["Quick", "Cooling", "Comfort Food"],
    icon: "milk",
    cuisine: "Indian",
    nutrition: { calories: 190, protein: 6, carbs: 34, fat: 3, fiber: 1 },
  },
  {
    id: "28",
    title: "Instant Rava Dosa",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 87,
    ingredients: ["Semolina", "Rice flour", "Cumin seeds", "Black pepper", "Onion", "Coriander leaves"],
    steps: ["Mix semolina, rice flour, spices with water", "Let rest 5 min", "Pour thin on hot tawa", "Cook until crispy, serve with chutney"],
    tags: ["Quick", "Crispy", "South Indian"],
    icon: "croissant",
    cuisine: "Indian",
    nutrition: { calories: 170, protein: 4, carbs: 30, fat: 4, fiber: 1 },
  },
  {
    id: "29",
    title: "Banana Lassi",
    cookTime: "5 min",
    difficulty: "Easy",
    servings: 2,
    kidApproval: 95,
    ingredients: ["Banana", "Yogurt", "Milk", "Sugar", "Cardamom", "Ice"],
    steps: ["Blend banana, yogurt, milk", "Add sugar and cardamom", "Blend until smooth", "Pour over ice and serve"],
    tags: ["Quick", "No-Cook", "Drink"],
    icon: "cup",
    cuisine: "Indian",
    nutrition: { calories: 160, protein: 5, carbs: 30, fat: 3, fiber: 1 },
  },
  {
    id: "30",
    title: "Maggi Masala Noodles",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 2,
    kidApproval: 97,
    ingredients: ["Maggi noodles", "Peas", "Carrots", "Onion", "Maggi masala", "Water"],
    steps: ["Boil water with veggies", "Add noodles and masala", "Cook 3-4 min stirring", "Serve hot"],
    tags: ["Quick", "Kid-Favorite", "One-Pot"],
    icon: "soup",
    cuisine: "Indian",
    nutrition: { calories: 310, protein: 8, carbs: 42, fat: 12, fiber: 2 },
  },
  // Italian Quick Recipes
  {
    id: "31",
    title: "Caprese Salad",
    cookTime: "5 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 82,
    ingredients: ["Fresh mozzarella", "Tomatoes", "Fresh basil", "Olive oil", "Balsamic glaze", "Salt"],
    steps: ["Slice mozzarella and tomatoes", "Arrange alternating on plate", "Tuck basil leaves between", "Drizzle oil and balsamic"],
    tags: ["Quick", "No-Cook", "Fresh"],
    icon: "salad",
    cuisine: "Italian",
    nutrition: { calories: 210, protein: 12, carbs: 6, fat: 16, fiber: 1 },
  },
  {
    id: "32",
    title: "Bruschetta",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 80,
    ingredients: ["Baguette", "Tomatoes", "Garlic", "Fresh basil", "Olive oil", "Salt"],
    steps: ["Toast baguette slices", "Dice tomatoes with basil and garlic", "Mix with olive oil and salt", "Spoon onto toast"],
    tags: ["Quick", "Appetizer", "Fresh"],
    icon: "wheat",
    cuisine: "Italian",
    nutrition: { calories: 180, protein: 5, carbs: 24, fat: 7, fiber: 2 },
  },
  {
    id: "33",
    title: "Aglio e Olio",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 88,
    ingredients: ["Spaghetti", "Garlic", "Olive oil", "Red pepper flakes", "Parsley", "Parmesan"],
    steps: ["Boil pasta until al dente", "Sauté garlic in olive oil", "Toss pasta with garlic oil", "Top with parsley and cheese"],
    tags: ["Quick", "Classic", "Simple"],
    icon: "wheat",
    cuisine: "Italian",
    nutrition: { calories: 340, protein: 10, carbs: 44, fat: 14, fiber: 2 },
  },
  {
    id: "34",
    title: "Pesto Pasta",
    cookTime: "12 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 91,
    ingredients: ["Penne pasta", "Basil pesto", "Cherry tomatoes", "Parmesan", "Pine nuts", "Olive oil"],
    steps: ["Cook pasta until al dente", "Halve cherry tomatoes", "Toss pasta with pesto", "Top with tomatoes, cheese and pine nuts"],
    tags: ["Quick", "Kid-Favorite", "One-Pot"],
    icon: "leafy",
    cuisine: "Italian",
    nutrition: { calories: 380, protein: 12, carbs: 42, fat: 18, fiber: 3 },
  },
  // Mexican Quick Recipes
  {
    id: "35",
    title: "Cheese Quesadillas",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 96,
    ingredients: ["Flour tortillas", "Cheddar cheese", "Mozzarella", "Butter", "Salsa", "Sour cream"],
    steps: ["Place cheese on half tortilla", "Fold and press", "Cook on pan 2 min each side", "Cut into wedges and serve"],
    tags: ["Quick", "Kid-Favorite", "Cheesy"],
    icon: "flame",
    cuisine: "Mexican",
    nutrition: { calories: 290, protein: 14, carbs: 26, fat: 15, fiber: 1 },
  },
  {
    id: "36",
    title: "Guacamole Bowl",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 78,
    ingredients: ["Avocados", "Lime", "Tomato", "Onion", "Cilantro", "Tortilla chips"],
    steps: ["Mash avocados in bowl", "Add diced tomato and onion", "Squeeze lime and mix", "Serve with chips"],
    tags: ["Quick", "No-Cook", "Healthy"],
    icon: "salad",
    cuisine: "Mexican",
    nutrition: { calories: 250, protein: 4, carbs: 18, fat: 20, fiber: 8 },
  },
  {
    id: "37",
    title: "Bean Tostadas",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 84,
    ingredients: ["Tostada shells", "Refried beans", "Lettuce", "Cheese", "Sour cream", "Salsa"],
    steps: ["Warm beans in pan", "Spread beans on tostada shells", "Layer lettuce and cheese", "Top with sour cream and salsa"],
    tags: ["Quick", "Crunchy", "Protein"],
    icon: "bean",
    cuisine: "Mexican",
    nutrition: { calories: 270, protein: 11, carbs: 30, fat: 12, fiber: 6 },
  },
  {
    id: "38",
    title: "Loaded Nachos",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 6,
    kidApproval: 95,
    ingredients: ["Tortilla chips", "Cheddar cheese", "Black beans", "Jalapeños", "Sour cream", "Salsa"],
    steps: ["Spread chips on baking sheet", "Top with cheese and beans", "Broil 3-4 minutes", "Add sour cream and salsa"],
    tags: ["Quick", "Kid-Favorite", "Sharing"],
    icon: "flame",
    cuisine: "Mexican",
    nutrition: { calories: 320, protein: 10, carbs: 34, fat: 16, fiber: 4 },
  },
  // Indian Quick Recipes
  {
    id: "39",
    title: "Masala Toast",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 88,
    ingredients: ["Bread slices", "Butter", "Chaat masala", "Onion", "Tomato", "Green chutney"],
    steps: ["Butter bread slices", "Top with sliced onion and tomato", "Sprinkle chaat masala", "Toast on pan until crispy"],
    tags: ["Quick", "Breakfast", "Street-Food"],
    icon: "sandwich",
    cuisine: "Indian",
    nutrition: { calories: 200, protein: 5, carbs: 28, fat: 8, fiber: 2 },
  },
  {
    id: "40",
    title: "Dahi Chaat",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 82,
    ingredients: ["Yogurt", "Boiled potatoes", "Chickpeas", "Tamarind chutney", "Chaat masala", "Sev"],
    steps: ["Dice boiled potatoes", "Layer potatoes and chickpeas", "Top with yogurt and chutneys", "Garnish with sev and masala"],
    tags: ["Quick", "No-Cook", "Tangy"],
    icon: "cup",
    cuisine: "Indian",
    nutrition: { calories: 220, protein: 8, carbs: 30, fat: 8, fiber: 3 },
  },
  {
    id: "41",
    title: "Besan Cheela",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 85,
    ingredients: ["Chickpea flour", "Onion", "Tomato", "Green chili", "Coriander", "Salt"],
    steps: ["Mix flour with water to batter", "Add diced veggies and spices", "Pour on hot pan like pancake", "Cook 2 min each side"],
    tags: ["Quick", "Protein", "Gluten-Free"],
    icon: "egg",
    cuisine: "Indian",
    nutrition: { calories: 180, protein: 10, carbs: 22, fat: 6, fiber: 4 },
  },
  {
    id: "42",
    title: "Paneer Bhurji",
    cookTime: "12 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 90,
    ingredients: ["Paneer", "Onion", "Tomato", "Green peas", "Turmeric", "Cumin"],
    steps: ["Crumble paneer", "Sauté onion and tomato", "Add spices and peas", "Mix in paneer and cook 3 min"],
    tags: ["Quick", "Protein", "Veggie"],
    icon: "flame",
    cuisine: "Indian",
    nutrition: { calories: 260, protein: 16, carbs: 10, fat: 18, fiber: 2 },
  },
  // Chinese Quick Recipes
  {
    id: "43",
    title: "Egg Fried Rice",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 94,
    ingredients: ["Cooked rice", "Eggs", "Green onions", "Soy sauce", "Sesame oil", "Peas"],
    steps: ["Scramble eggs in hot wok", "Add rice and peas", "Season with soy sauce", "Toss with sesame oil and onions"],
    tags: ["Quick", "Kid-Favorite", "One-Pan"],
    icon: "egg",
    cuisine: "Chinese",
    nutrition: { calories: 310, protein: 10, carbs: 42, fat: 11, fiber: 2 },
  },
  {
    id: "44",
    title: "Sesame Noodles",
    cookTime: "12 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 90,
    ingredients: ["Noodles", "Soy sauce", "Sesame paste", "Rice vinegar", "Sugar", "Cucumber"],
    steps: ["Cook noodles and cool", "Whisk sauce ingredients", "Toss noodles with sauce", "Top with sliced cucumber"],
    tags: ["Quick", "Cold", "Nutty"],
    icon: "wheat",
    cuisine: "Chinese",
    nutrition: { calories: 290, protein: 9, carbs: 40, fat: 10, fiber: 2 },
  },
  {
    id: "45",
    title: "Stir-Fry Greens",
    cookTime: "8 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 75,
    ingredients: ["Bok choy", "Garlic", "Soy sauce", "Sesame oil", "Oyster sauce", "Ginger"],
    steps: ["Heat oil in wok", "Add garlic and ginger", "Toss in bok choy", "Season and stir-fry 3 min"],
    tags: ["Quick", "Healthy", "Veggie"],
    icon: "leafy",
    cuisine: "Chinese",
    nutrition: { calories: 80, protein: 4, carbs: 6, fat: 5, fiber: 2 },
  },
  {
    id: "46",
    title: "Wonton Soup",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 86,
    ingredients: ["Frozen wontons", "Chicken broth", "Bok choy", "Green onions", "Soy sauce", "Sesame oil"],
    steps: ["Bring broth to boil", "Add frozen wontons", "Cook 5-6 minutes", "Add bok choy and season"],
    tags: ["Quick", "Warm", "Comforting"],
    icon: "soup",
    cuisine: "Chinese",
    nutrition: { calories: 230, protein: 12, carbs: 28, fat: 8, fiber: 1 },
  },
  // Japanese Quick Recipes
  {
    id: "47",
    title: "Miso Soup",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 80,
    ingredients: ["Miso paste", "Dashi stock", "Tofu", "Seaweed", "Green onions", "Mushrooms"],
    steps: ["Heat dashi stock", "Add tofu and seaweed", "Dissolve miso paste in broth", "Garnish with green onions"],
    tags: ["Quick", "Warm", "Traditional"],
    icon: "soup",
    cuisine: "Japanese",
    nutrition: { calories: 90, protein: 6, carbs: 8, fat: 4, fiber: 1 },
  },
  {
    id: "48",
    title: "Edamame Rice Bowl",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 84,
    ingredients: ["Cooked rice", "Edamame", "Soy sauce", "Rice vinegar", "Sesame seeds", "Nori"],
    steps: ["Warm rice and edamame", "Season with soy and vinegar", "Top with sesame seeds", "Garnish with nori strips"],
    tags: ["Quick", "Protein", "Healthy"],
    icon: "bean",
    cuisine: "Japanese",
    nutrition: { calories: 280, protein: 12, carbs: 40, fat: 8, fiber: 4 },
  },
  {
    id: "49",
    title: "Tamago (Egg Omelette)",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 2,
    kidApproval: 88,
    ingredients: ["Eggs", "Sugar", "Soy sauce", "Mirin", "Dashi", "Oil"],
    steps: ["Whisk eggs with seasonings", "Pour thin layer in pan", "Roll when set", "Repeat layers and slice"],
    tags: ["Quick", "Breakfast", "Traditional"],
    icon: "egg",
    cuisine: "Japanese",
    nutrition: { calories: 160, protein: 12, carbs: 4, fat: 11, fiber: 0 },
  },
  {
    id: "50",
    title: "Onigiri Rice Balls",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 6,
    kidApproval: 92,
    ingredients: ["Sushi rice", "Nori sheets", "Salt", "Tuna mayo", "Sesame seeds", "Soy sauce"],
    steps: ["Wet hands and salt lightly", "Shape rice into triangles", "Add filling in center", "Wrap with nori strip"],
    tags: ["Quick", "Fun", "Portable"],
    icon: "circle",
    cuisine: "Japanese",
    nutrition: { calories: 200, protein: 8, carbs: 34, fat: 4, fiber: 1 },
  },
  // Mediterranean Quick Recipes
  {
    id: "51",
    title: "Hummus Plate",
    cookTime: "5 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 82,
    ingredients: ["Hummus", "Pita bread", "Cucumber", "Cherry tomatoes", "Olives", "Olive oil"],
    steps: ["Spread hummus on plate", "Drizzle with olive oil", "Arrange veggies around", "Warm and slice pita"],
    tags: ["Quick", "No-Cook", "Healthy"],
    icon: "salad",
    cuisine: "Mediterranean",
    nutrition: { calories: 240, protein: 8, carbs: 28, fat: 12, fiber: 5 },
  },
  {
    id: "52",
    title: "Greek Salad",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 76,
    ingredients: ["Cucumber", "Tomatoes", "Red onion", "Feta cheese", "Olives", "Olive oil"],
    steps: ["Chop cucumber and tomatoes", "Slice onion thinly", "Combine with olives and feta", "Dress with oil and oregano"],
    tags: ["Quick", "No-Cook", "Fresh"],
    icon: "salad",
    cuisine: "Mediterranean",
    nutrition: { calories: 190, protein: 6, carbs: 10, fat: 15, fiber: 3 },
  },
  {
    id: "53",
    title: "Pita Pockets",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 86,
    ingredients: ["Pita bread", "Falafel (premade)", "Lettuce", "Tomato", "Tahini", "Pickles"],
    steps: ["Warm pita and falafel", "Cut pita in half to open", "Stuff with falafel and veggies", "Drizzle tahini inside"],
    tags: ["Quick", "Filling", "Portable"],
    icon: "sandwich",
    cuisine: "Mediterranean",
    nutrition: { calories: 310, protein: 12, carbs: 36, fat: 14, fiber: 5 },
  },
  // American Quick Recipes
  {
    id: "54",
    title: "PB&J Rollups",
    cookTime: "5 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 96,
    ingredients: ["Tortillas", "Peanut butter", "Strawberry jam", "Banana", "Honey", "Granola"],
    steps: ["Spread PB and jam on tortilla", "Place banana slices in line", "Roll tightly", "Slice into pinwheels"],
    tags: ["Quick", "No-Cook", "Kid-Favorite"],
    icon: "cookie",
    cuisine: "American",
    nutrition: { calories: 280, protein: 8, carbs: 36, fat: 12, fiber: 3 },
  },
  {
    id: "55",
    title: "Scrambled Eggs on Toast",
    cookTime: "8 min",
    difficulty: "Easy",
    servings: 2,
    kidApproval: 92,
    ingredients: ["Eggs", "Butter", "Toast", "Salt", "Pepper", "Chives"],
    steps: ["Whisk eggs with salt", "Melt butter in pan", "Scramble eggs gently", "Serve on buttered toast"],
    tags: ["Quick", "Breakfast", "Protein"],
    icon: "egg",
    cuisine: "American",
    nutrition: { calories: 250, protein: 14, carbs: 18, fat: 14, fiber: 1 },
  },
  {
    id: "56",
    title: "Trail Mix Bites",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 8,
    kidApproval: 90,
    ingredients: ["Oats", "Peanut butter", "Honey", "Chocolate chips", "Raisins", "Coconut flakes"],
    steps: ["Mix all ingredients in bowl", "Roll into small balls", "Chill 5 minutes", "Serve or pack for snacks"],
    tags: ["Quick", "No-Bake", "Snack"],
    icon: "cookie",
    cuisine: "American",
    nutrition: { calories: 150, protein: 4, carbs: 20, fat: 7, fiber: 2 },
  },
  {
    id: "57",
    title: "Smoothie Bowl",
    cookTime: "5 min",
    difficulty: "Easy",
    servings: 2,
    kidApproval: 94,
    ingredients: ["Frozen berries", "Banana", "Yogurt", "Granola", "Honey", "Chia seeds"],
    steps: ["Blend berries, banana and yogurt", "Pour thick into bowl", "Top with granola and seeds", "Drizzle honey"],
    tags: ["Quick", "Breakfast", "Healthy"],
    icon: "cherry",
    cuisine: "American",
    nutrition: { calories: 220, protein: 8, carbs: 38, fat: 5, fiber: 5 },
  },
  // Thai Quick Recipes
  {
    id: "58",
    title: "Thai Peanut Noodles",
    cookTime: "12 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 88,
    ingredients: ["Rice noodles", "Peanut butter", "Soy sauce", "Lime", "Carrots", "Cilantro"],
    steps: ["Cook noodles per package", "Whisk peanut sauce", "Toss noodles with sauce", "Top with shredded carrots"],
    tags: ["Quick", "Nutty", "Flavorful"],
    icon: "wheat",
    cuisine: "Thai",
    nutrition: { calories: 320, protein: 10, carbs: 40, fat: 14, fiber: 3 },
  },
  {
    id: "59",
    title: "Fresh Spring Rolls",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 82,
    ingredients: ["Rice paper", "Shrimp", "Rice noodles", "Lettuce", "Mint", "Peanut dipping sauce"],
    steps: ["Soak rice paper in water", "Layer fillings on wrapper", "Roll tightly tucking sides", "Serve with peanut sauce"],
    tags: ["Quick", "No-Cook", "Fresh"],
    icon: "salad",
    cuisine: "Thai",
    nutrition: { calories: 180, protein: 10, carbs: 24, fat: 5, fiber: 2 },
  },
  {
    id: "60",
    title: "Mango Sticky Rice",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 93,
    ingredients: ["Sticky rice (precooked)", "Mango", "Coconut milk", "Sugar", "Salt", "Sesame seeds"],
    steps: ["Warm coconut milk with sugar", "Pour over sticky rice", "Slice mango", "Serve rice with mango and sesame"],
    tags: ["Quick", "Dessert", "Sweet"],
    icon: "apple",
    cuisine: "Thai",
    nutrition: { calories: 280, protein: 4, carbs: 48, fat: 8, fiber: 2 },
  },
];

export const commonAllergies = [
  "Dairy", "Eggs", "Peanuts", "Tree Nuts", "Wheat/Gluten", "Soy", "Fish", "Shellfish",
];

export const commonDislikes = [
  "Spicy food", "Mushrooms", "Onions", "Tomatoes", "Broccoli", "Fish", "Beans", "Spinach",
];

export const commonFavorites = [
  "Pasta", "Pizza", "Chicken nuggets", "Mac & cheese", "Rice", "Fruits", "Pancakes", "Sandwiches",
];

export const cuisineOptions = [
  "Italian", "Mexican", "Indian", "Chinese", "Japanese", "Mediterranean", "American", "Thai",
];
