import { Recipe } from "./types";

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    title: "Rainbow Veggie Wraps",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 92,
    ingredients: ["Tortillas", "Hummus", "Carrots", "Cucumber", "Bell peppers", "Cheese"],
    steps: ["Spread hummus on tortilla", "Layer sliced veggies", "Add cheese", "Roll tightly and slice"],
    tags: ["Quick", "No-Cook", "Veggie"],
    emoji: "🌯",
    cuisine: "Mediterranean",
    nutrition: { calories: 220, protein: 8, carbs: 28, fat: 9, fiber: 4 },
  },
  {
    id: "2",
    title: "Mini Pizza Faces",
    cookTime: "20 min",
    difficulty: "Easy",
    servings: 6,
    kidApproval: 98,
    ingredients: ["English muffins", "Pizza sauce", "Mozzarella", "Olives", "Cherry tomatoes", "Peppers"],
    steps: ["Preheat oven to 375°F", "Spread sauce on muffin halves", "Add cheese and toppings as faces", "Bake 10-12 minutes"],
    tags: ["Fun", "Kid-Favorite", "Interactive"],
    emoji: "🍕",
    cuisine: "Italian",
    nutrition: { calories: 280, protein: 12, carbs: 30, fat: 12, fiber: 2 },
  },
  {
    id: "3",
    title: "Banana Oat Pancakes",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 95,
    ingredients: ["Bananas", "Oats", "Eggs", "Cinnamon", "Honey", "Blueberries"],
    steps: ["Blend banana, oats, eggs and cinnamon", "Pour small circles on pan", "Cook 2 min each side", "Top with berries"],
    tags: ["Breakfast", "Healthy", "No Sugar Added"],
    emoji: "🥞",
    cuisine: "American",
    nutrition: { calories: 195, protein: 7, carbs: 32, fat: 5, fiber: 3 },
  },
  {
    id: "4",
    title: "Cheesy Broccoli Bites",
    cookTime: "25 min",
    difficulty: "Medium",
    servings: 12,
    kidApproval: 87,
    ingredients: ["Broccoli", "Cheddar cheese", "Breadcrumbs", "Eggs", "Garlic powder"],
    steps: ["Steam and chop broccoli", "Mix with cheese, breadcrumbs, egg", "Form into small balls", "Bake at 400°F for 15 min"],
    tags: ["Veggie Hidden", "Snack", "Freezer-Friendly"],
    emoji: "🥦",
    cuisine: "American",
    nutrition: { calories: 85, protein: 5, carbs: 8, fat: 4, fiber: 1 },
  },
  {
    id: "5",
    title: "Peanut Butter Noodles",
    cookTime: "12 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 90,
    ingredients: ["Spaghetti", "Peanut butter", "Soy sauce", "Honey", "Lime", "Carrots"],
    steps: ["Cook pasta al dente", "Whisk PB, soy, honey, lime", "Toss pasta with sauce", "Top with shredded carrots"],
    tags: ["Quick", "Protein-Rich", "One-Pot"],
    emoji: "🍝",
    cuisine: "Thai",
    nutrition: { calories: 340, protein: 14, carbs: 42, fat: 13, fiber: 3 },
  },
  {
    id: "6",
    title: "Berry Smoothie Bowl",
    cookTime: "5 min",
    difficulty: "Easy",
    servings: 2,
    kidApproval: 94,
    ingredients: ["Mixed berries", "Banana", "Yogurt", "Granola", "Chia seeds", "Honey"],
    steps: ["Blend berries, banana, yogurt until thick", "Pour into bowls", "Top with granola and chia", "Drizzle honey"],
    tags: ["Breakfast", "No-Cook", "Healthy"],
    emoji: "🫐",
    cuisine: "American",
    nutrition: { calories: 250, protein: 8, carbs: 45, fat: 5, fiber: 6 },
  },
  {
    id: "7",
    title: "Chicken Quesadillas",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 96,
    ingredients: ["Tortillas", "Shredded chicken", "Cheddar cheese", "Bell peppers", "Sour cream", "Salsa"],
    steps: ["Layer cheese and chicken on tortilla", "Add diced peppers", "Fold and cook on pan 3 min each side", "Slice into wedges"],
    tags: ["Quick", "Kid-Favorite", "Protein-Rich"],
    emoji: "🫔",
    cuisine: "Mexican",
    nutrition: { calories: 320, protein: 22, carbs: 28, fat: 14, fiber: 2 },
  },
  {
    id: "8",
    title: "Veggie Fried Rice",
    cookTime: "20 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 88,
    ingredients: ["Cooked rice", "Eggs", "Frozen peas & carrots", "Soy sauce", "Sesame oil", "Green onions"],
    steps: ["Scramble eggs in hot pan", "Add veggies and rice", "Season with soy sauce and sesame oil", "Toss and serve"],
    tags: ["One-Pot", "Veggie", "Leftover-Friendly"],
    emoji: "🍚",
    cuisine: "Chinese",
    nutrition: { calories: 260, protein: 9, carbs: 38, fat: 8, fiber: 3 },
  },
  {
    id: "9",
    title: "Fish Stick Tacos",
    cookTime: "18 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 85,
    ingredients: ["Fish sticks", "Small tortillas", "Shredded cabbage", "Lime", "Greek yogurt", "Avocado"],
    steps: ["Bake fish sticks per package directions", "Warm tortillas", "Top with cabbage, avocado, yogurt drizzle", "Squeeze lime on top"],
    tags: ["Fun", "Omega-3", "Interactive"],
    emoji: "🌮",
    cuisine: "Mexican",
    nutrition: { calories: 275, protein: 15, carbs: 30, fat: 11, fiber: 4 },
  },
  {
    id: "10",
    title: "Mac & Cheese Cups",
    cookTime: "25 min",
    difficulty: "Easy",
    servings: 12,
    kidApproval: 97,
    ingredients: ["Elbow macaroni", "Cheddar cheese", "Milk", "Butter", "Breadcrumbs", "Parmesan"],
    steps: ["Cook macaroni al dente", "Mix with cheese sauce", "Spoon into muffin tin", "Top with breadcrumbs and bake 12 min"],
    tags: ["Kid-Favorite", "Freezer-Friendly", "Fun"],
    emoji: "🧀",
    cuisine: "American",
    nutrition: { calories: 180, protein: 8, carbs: 22, fat: 7, fiber: 1 },
  },
  {
    id: "11",
    title: "Teriyaki Chicken Skewers",
    cookTime: "20 min",
    difficulty: "Medium",
    servings: 4,
    kidApproval: 91,
    ingredients: ["Chicken breast", "Teriyaki sauce", "Pineapple chunks", "Bell peppers", "Rice", "Sesame seeds"],
    steps: ["Cut chicken into cubes", "Thread onto skewers with pineapple and peppers", "Brush with teriyaki", "Grill or bake 12 min, serve over rice"],
    tags: ["Interactive", "Protein-Rich", "Sweet"],
    emoji: "🍢",
    cuisine: "Japanese",
    nutrition: { calories: 310, protein: 26, carbs: 35, fat: 6, fiber: 2 },
  },
  {
    id: "12",
    title: "Hidden Veggie Pasta Sauce",
    cookTime: "25 min",
    difficulty: "Easy",
    servings: 6,
    kidApproval: 93,
    ingredients: ["Pasta", "Tomato sauce", "Zucchini", "Carrots", "Spinach", "Parmesan"],
    steps: ["Blend zucchini, carrots, spinach into tomato sauce", "Simmer 10 min", "Cook pasta", "Toss and top with parmesan"],
    tags: ["Veggie Hidden", "Batch-Cook", "Classic"],
    emoji: "🍝",
    cuisine: "Italian",
    nutrition: { calories: 285, protein: 11, carbs: 42, fat: 8, fiber: 5 },
  },
  {
    id: "13",
    title: "Mini Meatball Soup",
    cookTime: "25 min",
    difficulty: "Medium",
    servings: 6,
    kidApproval: 89,
    ingredients: ["Ground turkey", "Chicken broth", "Small pasta", "Carrots", "Spinach", "Parmesan"],
    steps: ["Roll tiny meatballs from seasoned turkey", "Simmer in broth with carrots and pasta", "Add spinach last minute", "Serve with parmesan"],
    tags: ["Warm", "Protein-Rich", "Comforting"],
    emoji: "🍲",
    cuisine: "Italian",
    nutrition: { calories: 230, protein: 18, carbs: 22, fat: 7, fiber: 3 },
  },
  {
    id: "14",
    title: "Butter Chicken Mild",
    cookTime: "30 min",
    difficulty: "Medium",
    servings: 4,
    kidApproval: 86,
    ingredients: ["Chicken thighs", "Tomato puree", "Cream", "Butter", "Garam masala", "Rice"],
    steps: ["Cook chicken in butter", "Add tomato puree and mild spices", "Stir in cream and simmer 15 min", "Serve over rice"],
    tags: ["Mild", "Creamy", "Protein-Rich"],
    emoji: "🍛",
    cuisine: "Indian",
    nutrition: { calories: 350, protein: 24, carbs: 30, fat: 15, fiber: 2 },
  },
  {
    id: "15",
    title: "Fruit & Yogurt Parfait",
    cookTime: "5 min",
    difficulty: "Easy",
    servings: 2,
    kidApproval: 96,
    ingredients: ["Greek yogurt", "Granola", "Strawberries", "Blueberries", "Honey", "Chia seeds"],
    steps: ["Layer yogurt in glass", "Add granola and berries", "Repeat layers", "Drizzle honey and chia on top"],
    tags: ["Breakfast", "No-Cook", "Healthy"],
    emoji: "🍓",
    cuisine: "American",
    nutrition: { calories: 210, protein: 12, carbs: 32, fat: 5, fiber: 4 },
  },
  {
    id: "16",
    title: "Sweet Potato Fries & Dip",
    cookTime: "28 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 92,
    ingredients: ["Sweet potatoes", "Olive oil", "Paprika", "Garlic powder", "Greek yogurt", "Ketchup"],
    steps: ["Cut sweet potatoes into fries", "Toss with oil and spices", "Bake at 425°F for 22 min", "Serve with yogurt dip"],
    tags: ["Snack", "Healthy", "Veggie"],
    emoji: "🍠",
    cuisine: "American",
    nutrition: { calories: 185, protein: 4, carbs: 32, fat: 5, fiber: 5 },
  },
  {
    id: "17",
    title: "Veggie Pulao",
    cookTime: "25 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 90,
    ingredients: ["Basmati rice", "Mixed veggies", "Ghee", "Cumin seeds", "Bay leaf", "Green peas"],
    steps: ["Sauté cumin and bay leaf in ghee", "Add veggies and rice", "Add water and cook covered 15 min", "Fluff with fork and serve"],
    tags: ["One-Pot", "Veggie", "Mild"],
    emoji: "🍚",
    cuisine: "Indian",
    nutrition: { calories: 270, protein: 6, carbs: 45, fat: 7, fiber: 3 },
  },
  {
    id: "18",
    title: "Mini Dosa with Chutney",
    cookTime: "20 min",
    difficulty: "Medium",
    servings: 6,
    kidApproval: 88,
    ingredients: ["Dosa batter", "Ghee", "Coconut chutney", "Potatoes", "Mustard seeds", "Curry leaves"],
    steps: ["Heat pan and spread batter thin", "Drizzle ghee, cook until crispy", "Fill with potato masala", "Serve with coconut chutney"],
    tags: ["Crispy", "South Indian", "Fun"],
    emoji: "🫓",
    cuisine: "Indian",
    nutrition: { calories: 195, protein: 5, carbs: 30, fat: 6, fiber: 2 },
  },
  {
    id: "19",
    title: "Aloo Paratha",
    cookTime: "25 min",
    difficulty: "Medium",
    servings: 4,
    kidApproval: 94,
    ingredients: ["Whole wheat flour", "Potatoes", "Butter", "Cumin powder", "Coriander", "Yogurt"],
    steps: ["Make dough and potato filling", "Stuff dough balls with filling", "Roll out and cook on tawa with butter", "Serve with yogurt"],
    tags: ["North Indian", "Comforting", "Kid-Favorite"],
    emoji: "🫓",
    cuisine: "Indian",
    nutrition: { calories: 240, protein: 6, carbs: 35, fat: 9, fiber: 3 },
  },
  {
    id: "20",
    title: "Paneer Tikka Bites",
    cookTime: "20 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 91,
    ingredients: ["Paneer", "Yogurt", "Turmeric", "Bell peppers", "Lemon", "Chaat masala"],
    steps: ["Cube paneer and marinate in spiced yogurt", "Thread onto skewers with peppers", "Grill or bake 12 min", "Squeeze lemon and sprinkle chaat masala"],
    tags: ["Protein-Rich", "Interactive", "Mild"],
    emoji: "🧀",
    cuisine: "Indian",
    nutrition: { calories: 220, protein: 14, carbs: 8, fat: 15, fiber: 1 },
  },
  {
    id: "21",
    title: "Dal Tadka",
    cookTime: "25 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 85,
    ingredients: ["Yellow lentils", "Tomatoes", "Garlic", "Cumin", "Ghee", "Rice"],
    steps: ["Boil lentils until soft", "Prepare tadka with ghee, garlic, cumin", "Pour over lentils with tomatoes", "Serve over steamed rice"],
    tags: ["Protein-Rich", "Comforting", "Mild"],
    emoji: "🍲",
    cuisine: "Indian",
    nutrition: { calories: 260, protein: 14, carbs: 38, fat: 6, fiber: 8 },
  },
  {
    id: "22",
    title: "Idli with Sambar",
    cookTime: "20 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 87,
    ingredients: ["Idli batter", "Mixed veggies", "Sambar powder", "Tamarind", "Mustard seeds", "Coconut chutney"],
    steps: ["Steam idli batter in moulds for 10 min", "Cook veggies in tamarind sambar", "Temper with mustard seeds", "Serve idlis with sambar and chutney"],
    tags: ["South Indian", "Healthy", "Steamed"],
    emoji: "⚪",
    cuisine: "Indian",
    nutrition: { calories: 180, protein: 7, carbs: 32, fat: 3, fiber: 4 },
  },
  {
    id: "23",
    title: "Chole Rice Bowl",
    cookTime: "25 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 86,
    ingredients: ["Chickpeas", "Onion", "Tomatoes", "Chole masala", "Rice", "Lemon"],
    steps: ["Sauté onions and tomatoes", "Add chickpeas and chole masala", "Simmer 15 min", "Serve over rice with lemon squeeze"],
    tags: ["Protein-Rich", "Mild", "One-Pot"],
    emoji: "🫘",
    cuisine: "Indian",
    nutrition: { calories: 290, protein: 12, carbs: 45, fat: 6, fiber: 9 },
  },
  {
    id: "24",
    title: "Khichdi",
    cookTime: "20 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 83,
    ingredients: ["Rice", "Moong dal", "Ghee", "Turmeric", "Cumin", "Mixed veggies"],
    steps: ["Wash rice and dal together", "Pressure cook with veggies, turmeric, water", "Temper with ghee and cumin", "Serve warm with a dollop of ghee"],
    tags: ["Comfort Food", "One-Pot", "Gentle"],
    emoji: "🍛",
    cuisine: "Indian",
    nutrition: { calories: 230, protein: 9, carbs: 38, fat: 5, fiber: 4 },
  },
];

  {
    id: "25",
    title: "Poha (Flattened Rice)",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 91,
    ingredients: ["Flattened rice", "Onion", "Green peas", "Peanuts", "Turmeric", "Lemon"],
    steps: ["Rinse and drain poha", "Sauté onion, peanuts, peas", "Add turmeric and poha, toss", "Squeeze lemon and serve"],
    tags: ["Quick", "Mild", "Breakfast"],
    emoji: "🍚",
    cuisine: "Indian",
    nutrition: { calories: 200, protein: 5, carbs: 32, fat: 6, fiber: 2 },
  },
  {
    id: "26",
    title: "Bread Upma",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 3,
    kidApproval: 85,
    ingredients: ["Bread slices", "Onion", "Tomato", "Mustard seeds", "Curry leaves", "Green chili"],
    steps: ["Cube and lightly toast bread", "Temper mustard seeds and curry leaves", "Add onion, tomato, sauté", "Toss in bread cubes and serve"],
    tags: ["Quick", "Budget", "Breakfast"],
    emoji: "🍞",
    cuisine: "Indian",
    nutrition: { calories: 180, protein: 5, carbs: 28, fat: 5, fiber: 2 },
  },
  {
    id: "27",
    title: "Curd Rice",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 88,
    ingredients: ["Cooked rice", "Yogurt", "Mustard seeds", "Curry leaves", "Pomegranate seeds", "Salt"],
    steps: ["Mix cooled rice with yogurt", "Temper mustard seeds and curry leaves", "Pour over rice and mix", "Garnish with pomegranate"],
    tags: ["Quick", "Cooling", "Comfort Food"],
    emoji: "🥛",
    cuisine: "Indian",
    nutrition: { calories: 190, protein: 6, carbs: 34, fat: 3, fiber: 1 },
  },
  {
    id: "28",
    title: "Instant Rava Dosa",
    cookTime: "15 min",
    difficulty: "Easy",
    servings: 4,
    kidApproval: 87,
    ingredients: ["Semolina", "Rice flour", "Cumin seeds", "Black pepper", "Onion", "Coriander leaves"],
    steps: ["Mix semolina, rice flour, spices with water", "Let rest 5 min", "Pour thin on hot tawa", "Cook until crispy, serve with chutney"],
    tags: ["Quick", "Crispy", "South Indian"],
    emoji: "🫓",
    cuisine: "Indian",
    nutrition: { calories: 170, protein: 4, carbs: 30, fat: 4, fiber: 1 },
  },
  {
    id: "29",
    title: "Banana Lassi",
    cookTime: "5 min",
    difficulty: "Easy",
    servings: 2,
    kidApproval: 95,
    ingredients: ["Banana", "Yogurt", "Milk", "Sugar", "Cardamom", "Ice"],
    steps: ["Blend banana, yogurt, milk", "Add sugar and cardamom", "Blend until smooth", "Pour over ice and serve"],
    tags: ["Quick", "No-Cook", "Drink"],
    emoji: "🍌",
    cuisine: "Indian",
    nutrition: { calories: 160, protein: 5, carbs: 30, fat: 3, fiber: 1 },
  },
  {
    id: "30",
    title: "Maggi Masala Noodles",
    cookTime: "10 min",
    difficulty: "Easy",
    servings: 2,
    kidApproval: 97,
    ingredients: ["Maggi noodles", "Peas", "Carrots", "Onion", "Maggi masala", "Water"],
    steps: ["Boil water with veggies", "Add noodles and masala", "Cook 3-4 min stirring", "Serve hot"],
    tags: ["Quick", "Kid-Favorite", "One-Pot"],
    emoji: "🍜",
    cuisine: "Indian",
    nutrition: { calories: 310, protein: 8, carbs: 42, fat: 12, fiber: 2 },
  },

export const commonAllergies = [
  "Dairy", "Eggs", "Peanuts", "Tree Nuts", "Wheat/Gluten", "Soy", "Fish", "Shellfish",
];

export const commonDislikes = [
  "Spicy food", "Mushrooms", "Onions", "Tomatoes", "Broccoli", "Fish", "Beans", "Spinach",
];

export const commonFavorites = [
  "Pasta", "Pizza", "Chicken nuggets", "Mac & cheese", "Rice", "Fruits", "Pancakes", "Sandwiches",
];

export const cuisineOptions = [
  "Italian", "Mexican", "Indian", "Chinese", "Japanese", "Mediterranean", "American", "Thai",
];
